grad2rad=pi/180;
% ggg=figure('Position',[40 4 2000 800]);
% subplot(3,2,1)
% plot3(profile(:,1),profile(:,2),profile(:,3),'b')
% title('Flight Path Generated By PROGEN')
% xlabel('east(longitude) (grad)')
% ylabel('north(latitude) (grad)')
% zlabel('up (meters)')
% grid
% 
% subplot(3,2,2)
% plot(time,roll(:),'r')
% hold on
% plot(time,pitch(:),'g')
% hold on
% plot(time,yaw(:),'b')
% title('Euler Angles Generated By PROGEN')
% xlabel('time (s)')
% ylabel('roll(r) pitch(g) yaw(b) (grad)')
% grid
% 
% 
% 
% subplot(3,2,3)
% plot3(tru_long_new*180/pi,tru_lat_new*180/pi,tru_height_new,'b')
% title('Flight Path from inertial navigation  ')
% xlabel('east(longitude) (grad)')
% ylabel('north(latitude) (grad)')
% zlabel('up (meters)')
% grid
% 
% subplot(3,2,4)
% plot(ttt,tru_roll_new,'r')
% hold on
% plot(ttt,tru_pitch_new,'g')
% hold on
% plot(ttt,tru_yaw_new,'b')
% title('  Euler Angles from inertial navigation  ')
% ylabel('roll(r) pitch(g) yaw(b) (grad)')
% xlabel('time in s')
% grid

lengthTs=length(Ts_EE_to_Base_true)-1;
for ii=1:lengthTs
    TTT1=T_Base_to_DTM*Ts_EE_to_Base_true{ii};
    TTT2=T_Base_to_DTM*Ts_EE_to_Base_drifted{ii};
vv1x(ii)=TTT1(1,4);
vv2x(ii)=TTT2(1,4);
vv1y(ii)=TTT1(2,4);
vv2y(ii)=TTT2(2,4);
vv1z(ii)=TTT1(3,4);
vv2z(ii)=TTT2(3,4);
end
global xxs;
figure(xxs);
% global lonlathp xyz1p;
% zz1=[lat lon hint];  %initial position    
% lonlathp=[zz1(2)/grad2rad zz1(1)/grad2rad hint];
% xyz1p=llh2xyz(zz1);


% % % subplot(1,2,1)
% % % plot(time,profile(:,4),'r')
% % % hold on
% % % plot(time,profile(:,5),'g')
% % % hold on
% % % plot(time,profile(:,6),'b')
% % % %axis equal
% % % title('Flight velocities Generated By PROGEN')
% % % xlabel('time (s)')
% % % ylabel('vx(r) vy(g) vz(b) (meters/s)')
% % % grid
% figure
% plot3(bx_constructedPath,by_constructedPath,bz_constructedPath,'LineWidth',2)
% hold on
% % plot3(beforeMovment_Base(1,:),beforeMovment_Base(2,:),beforeMovment_Base(3,:),'*r','LineWidth',0.001)
% %axis equal
% title('Flight Path ')
% xlabel('east(meters)')
% ylabel('north(meters)')
% zlabel('up (meters)')
% grid

subplot(1,2,2)
hold on
plot3(vv1x(:),vv1y(:),vv1z(:),'r')
hold on
plot3(vv2x(:),vv2y(:),vv2z(:),'g')
title('Flight Path true(r) vs inertial nav(g) and vision-based nav(b)  ')
xlabel('east(longitude) (m)')
ylabel('north(latitude) (m)')
zlabel('up (meters)')
grid
figure(xxs);
subplot(1,2,2)
grid